export const leadsSteps = [
  //first step
  {
    title: 'Company Info',
    fields: [
      { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'Company Name', required: true },
      {
        key: 'leadsMedical', label: 'Medical', type: 'select', placeholder: 'Please Specify', options: [
          { label: 'Yes', value: 'Yes' },
          { label: 'No', value: 'No' },
        ]
      },
      {
        key: 'leadsBusinessType', label: 'Business Type', type: 'select', placeholder: 'Select Business Type', options: [
          { label: 'Retail', value: 'retail' },
          { label: 'Wholesale', value: 'wholesale' },
          { label: 'Service', value: 'service' },
          { label: 'Manufacturing', value: 'manufacturing' },
          { label: 'Other', value: 'other' }
        ]
      },
      { key: 'leadsWebsite', label: 'Website', type: 'url', placeholder: 'https://example.com', required: false },
      { key: 'leadsCompanyEmail', label: 'Email', type: 'email', placeholder: 'email@example.com', required: true },
      { key: 'leadsCompanyPhoneNumber', label: 'Phone Number', type: 'tel', placeholder: '123-456-7890', required: true },
      { key: 'leadsFaxNumber', label: 'Fax Number', type: 'tel', placeholder: '123-456-7890', required: false },
      {
        key: 'leadsCompanyCountry', label: 'Country', type: 'select', placeholder: 'Select Your Country', required: true, options: [
          { label: 'Afghanistan', value: 'Afghanistan' },
          { label: 'Albania', value: 'Albania' },
          { label: 'Algeria', value: 'Algeria' },
          { label: 'Andorra', value: 'Andorra' },
          { label: 'Angola', value: 'Angola' },
          { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
          { label: 'Argentina', value: 'Argentina' },
          { label: 'Armenia', value: 'Armenia' },
          { label: 'Australia', value: 'Australia' },
          { label: 'Austria', value: 'Austria' },
          { label: 'Azerbaijan', value: 'Azerbaijan' },
          { label: 'Bahamas', value: 'Bahamas' },
          { label: 'Bahrain', value: 'Bahrain' },
          { label: 'Bangladesh', value: 'Bangladesh' },
          { label: 'Barbados', value: 'Barbados' },
          { label: 'Belarus', value: 'Belarus' },
          { label: 'Belgium', value: 'Belgium' },
          { label: 'Belize', value: 'Belize' },
          { label: 'Benin', value: 'Benin' },
          { label: 'Bhutan', value: 'Bhutan' },
          { label: 'Bolivia', value: 'Bolivia' },
          { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
          { label: 'Botswana', value: 'Botswana' },
          { label: 'Brazil', value: 'Brazil' },
          { label: 'Brunei', value: 'Brunei' },
          { label: 'Bulgaria', value: 'Bulgaria' },
          { label: 'Burkina Faso', value: 'Burkina Faso' },
          { label: 'Burundi', value: 'Burundi' },
          { label: 'Cabo Verde', value: 'Cabo Verde' },
          { label: 'Cambodia', value: 'Cambodia' },
          { label: 'Cameroon', value: 'Cameroon' },
          { label: 'Canada', value: 'Canada' },
          { label: 'Central African Republic', value: 'Central African Republic' },
          { label: 'Chad', value: 'Chad' },
          { label: 'Chile', value: 'Chile' },
          { label: 'China', value: 'China' },
          { label: 'Colombia', value: 'Colombia' },
          { label: 'Comoros', value: 'Comoros' },
          { label: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)' },
          { label: 'Costa Rica', value: 'Costa Rica' },
          { label: 'Croatia', value: 'Croatia' },
          { label: 'Cuba', value: 'Cuba' },
          { label: 'Cyprus', value: 'Cyprus' },
          { label: 'Czech Republic', value: 'Czech Republic' },
          { label: 'Democratic Republic of the Congo', value: 'Democratic republic of the congo' },
          { label: 'Denmark', value: 'Denmark' },
          { label: 'Djibouti', value: 'Djibouti' },
          { label: 'Dominica', value: 'Dominica' },
          { label: 'Dominican Republic', value: 'Dominican Republic' },
          { label: 'Ecuador', value: 'Ecuador' },
          { label: 'Egypt', value: 'Egypt' },
          { label: 'El Salvador', value: 'El Salvador' },
          { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
          { label: 'Eritrea', value: 'Eritrea' },
          { label: 'Estonia', value: 'Estonia' },
          { label: 'Eswatini', value: 'Eswatini' },
          { label: 'Ethiopia', value: 'Ethiopia' },
          { label: 'Fiji', value: 'Fiji' },
          { label: 'Finland', value: 'Finland' },
          { label: 'France', value: 'France' },
          { label: 'Gabon', value: 'Gabon' },
          { label: 'Gambia', value: 'Gambia' },
          { label: 'Georgia', value: 'Georgia' },
          { label: 'Germany', value: 'Germany' },
          { label: 'Ghana', value: 'Ghana' },
          { label: 'Greece', value: 'Greece' },
          { label: 'Grenada', value: 'Grenada' },
          { label: 'Guatemala', value: 'Guatemala' },
          { label: 'Guinea', value: 'Guinea' },
          { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
          { label: 'Guyana', value: 'Guyana' },
          { label: 'Haiti', value: 'Haiti' },
          { label: 'Honduras', value: 'Honduras' },
          { label: 'Hungary', value: 'Hungary' },
          { label: 'Iceland', value: 'Iceland' },
          { label: 'India', value: 'India' },
          { label: 'Indonesia', value: 'Indonesia' },
          { label: 'Iran', value: 'Iran' },
          { label: 'Iraq', value: 'Iraq' },
          { label: 'Ireland', value: 'Ireland' },
          { label: 'Israel', value: 'Israel' },
          { label: 'Italy', value: 'Italy' },
          { label: 'Ivory Coast', value: 'Ivory Coast' },
          { label: 'Jamaica', value: 'Jamaica' },
          { label: 'Japan', value: 'Japan' },
          { label: 'Jordan', value: 'Jordan' },
          { label: 'Kazakhstan', value: 'Kazakhstan' },
          { label: 'Kenya', value: 'Kenya' },
          { label: 'Kiribati', value: 'Kiribati' },
          { label: 'Kuwait', value: 'Kuwait' },
          { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
          { label: 'Laos', value: 'Laos' },
          { label: 'Latvia', value: 'Latvia' },
          { label: 'Lebanon', value: 'Lebanon' },
          { label: 'Lesotho', value: 'Lesotho' },
          { label: 'Liberia', value: 'Liberia' },
          { label: 'Libya', value: 'Libya' },
          { label: 'Liechtenstein', value: 'Liechtenstein' },
          { label: 'Lithuania', value: 'Lithuania' },
          { label: 'Luxembourg', value: 'Luxembourg' },
          { label: 'Madagascar', value: 'Madagascar' },
          { label: 'Malawi', value: 'Malawi' },
          { label: 'Malaysia', value: 'Malaysia' },
          { label: 'Maldives', value: 'Maldives' },
          { label: 'Mali', value: 'Mali' },
          { label: 'Malta', value: 'Malta' },
          { label: 'Marshall Islands', value: 'Marshall Islands' },
          { label: 'Mauritania', value: 'Mauritania' },
          { label: 'Mauritius', value: 'Mauritius' },
          { label: 'Mexico', value: 'Mexico' },
          { label: 'Micronesia', value: 'Micronesia' },
          { label: 'Moldova', value: 'Moldova' },
          { label: 'Monaco', value: 'Monaco' },
          { label: 'Mongolia', value: 'Mongolia' },
          { label: 'Montenegro', value: 'Montenegro' },
          { label: 'Morocco', value: 'Morocco' },
          { label: 'Mozambique', value: 'Mozambique' },
          { label: 'Myanmar', value: 'Myanmar' },
          { label: 'Namibia', value: 'Namibia' },
          { label: 'Nauru', value: 'Nauru' },
          { label: 'Nepal', value: 'Nepal' },
          { label: 'Netherlands', value: 'Netherlands' },
          { label: 'New Zealand', value: 'New Zealand' },
          { label: 'Nicaragua', value: 'Nicaragua' },
          { label: 'Niger', value: 'Niger' },
          { label: 'Nigeria', value: 'Nigeria' },
          { label: 'North Korea', value: 'North Korea' },
          { label: 'North Macedonia', value: 'North macedonia' },
          { label: 'Norway', value: 'Norway' },
          { label: 'Oman', value: 'Oman' },
          { label: 'Pakistan', value: 'Pakistan' },
          { label: 'Palau', value: 'Palau' },
          { label: 'Palestine', value: 'Palestine' },
          { label: 'Panama', value: 'Panama' },
          { label: 'Papua New Guinea', value: 'Papua New Guinea' },
          { label: 'Paraguay', value: 'Paraguay' },
          { label: 'Peru', value: 'Peru' },
          { label: 'Philippines', value: 'Philippines' },
          { label: 'Poland', value: 'Poland' },
          { label: 'Portugal', value: 'Portugal' },
          { label: 'Qatar', value: 'Qatar' },
          { label: 'Romania', value: 'Romania' },
          { label: 'Russia', value: 'Russia' },
          { label: 'Rwanda', value: 'Rwanda' },
          { label: 'Saint Kitts and Nevis', value: 'Saint Kitts ad Nevis' },
          { label: 'Saint Lucia', value: 'saint lucia' },
          { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and The Grenadines' },
          { label: 'Samoa', value: 'Samoa' },
          { label: 'San Marino', value: 'San Marino' },
          { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
          { label: 'Saudi Arabia', value: 'Saudi Arabia' },
          { label: 'Senegal', value: 'Senegal' },
          { label: 'Serbia', value: 'Serbia' },
          { label: 'Seychelles', value: 'Seychelles' },
          { label: 'Sierra Leone', value: 'Sierra Leone' },
          { label: 'Singapore', value: 'Singapore' },
          { label: 'Slovakia', value: 'Slovakia' },
          { label: 'Slovenia', value: 'Slovenia' },
          { label: 'Solomon Islands', value: 'Solomon Islands' },
          { label: 'Somalia', value: 'Somalia' },
          { label: 'South Africa', value: 'South Africa' },
          { label: 'South Korea', value: 'South Korea' },
          { label: 'South Sudan', value: 'South Sudan' },
          { label: 'Spain', value: 'Spain' },
          { label: 'Sri Lanka', value: 'Sri Lanka' },
          { label: 'Sudan', value: 'Sudan' },
          { label: 'Suriname', value: 'Suriname' },
          { label: 'Sweden', value: 'Sweden' },
          { label: 'Switzerland', value: 'Switzerland' },
          { label: 'Syria', value: 'Syria' },
          { label: 'Taiwan', value: 'Taiwan' },
          { label: 'Tajikistan', value: 'Tajikistan' },
          { label: 'Tanzania', value: 'Tanzania' },
          { label: 'Thailand', value: 'Thailand' },
          { label: 'Timor-Leste', value: 'Timor-Leste' },
          { label: 'Togo', value: 'Togo' },
          { label: 'Tonga', value: 'Tonga' },
          { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
          { label: 'Tunisia', value: 'Tunisia' },
          { label: 'Turkey', value: 'Turkey' },
          { label: 'Turkmenistan', value: 'Turkmenistan' },
          { label: 'Tuvalu', value: 'Tuvalu' },
          { label: 'Uganda', value: 'Uganda' },
          { label: 'Ukraine', value: 'Ukraine' },
          { label: 'United Arab Emirates', value: 'United Arab Emirates' },
          { label: 'United Kingdom', value: 'United Kingdom' },
          { label: 'United States', value: 'United States' },
          { label: 'Uruguay', value: 'Uruguay' },
          { label: 'Uzbekistan', value: 'Uzbekistan' },
          { label: 'Vanuatu', value: 'Vanuatu' },
          { label: 'Vatican City', value: 'Vatican city' },
          { label: 'Venezuela', value: 'Venezuela' },
          { label: 'Vietnam', value: 'Vietnam' },
          { label: 'Yemen', value: 'Yemen' },
          { label: 'Zambia', value: 'Zambia' },
          { label: 'Zimbabwe', value: 'Zimbabwe' }
        ]
      },
      { key: 'leadsCompanyAddress1', label: 'Address 1', type: 'text', placeholder: '123 Main St, City, State, Zip', required: true },
      { key: 'leadsCompanyAddress2', label: 'Address 2', type: 'text', placeholder: 'Apartment, Suite, etc.', required: false },
      { key: 'leadsCopmanyCity', label: 'City', type: 'text', placeholder: 'Los Angeles', required: true },
      {
        key: 'leadsCompanyState', label: 'State', type: 'select', placeholder: 'Select State', required: true, options: [
          { label: 'Alabama', value: 'Alabama' },
          { label: 'Alaska', value: 'Alaska' },
          { label: 'Arizona', value: 'Arizona' },
          { label: 'Arkansas', value: 'Arkansas' },
          { label: 'California', value: 'California' },
          { label: 'Colorado', value: 'Colorado' },
          { label: 'Connecticut', value: 'Connecticut' },
          { label: 'Delaware', value: 'Delaware' },
          { label: 'Florida', value: 'Florida' },
          { label: 'Georgia', value: 'Georgia' },
          { label: 'Hawaii', value: 'Hawaii' },
          { label: 'Idaho', value: 'Idaho' },
          { label: 'Illinois', value: 'Illinois' },
          { label: 'Indiana', value: 'Indiana' },
          { label: 'Iowa', value: 'Iowa' },
          { label: 'Kansas', value: 'Kansas' },
          { label: 'Kentucky', value: 'Kentucky' },
          { label: 'Louisiana', value: 'Louisiana' },
          { label: 'Maine', value: 'Maine' },
          { label: 'Maryland', value: 'Maryland' },
          { label: 'Massachusetts', value: 'Massachusetts' },
          { label: 'Michigan', value: 'Michigan' },
          { label: 'Minnesota', value: 'Minnesota' },
          { label: 'Mississippi', value: 'Mississippi' },
          { label: 'Missouri', value: 'Missouri' },
          { label: 'Montana', value: 'Montana' },
          { label: 'Nebraska', value: 'Nebraska' },
          { label: 'Nevada', value: 'Nevada' },
          { label: 'New Hampshire', value: 'New Hampshire' },
          { label: 'New Jersey', value: 'New Jersey' },
          { label: 'New Mexico', value: 'New Mexico' },
          { label: 'New York', value: 'New York' },
          { label: 'North Carolina', value: 'North Carolina' },
          { label: 'North Dakota', value: 'North Dakota' },
          { label: 'Ohio', value: 'Ohio' },
          { label: 'Oklahoma', value: 'Oklahoma' },
          { label: 'Oregon', value: 'Oregon' },
          { label: 'Pennsylvania', value: 'Pennsylvania' },
          { label: 'Rhode Island', value: 'Rhode Island' },
          { label: 'South Carolina', value: 'South Carolina' },
          { label: 'South Dakota', value: 'South Dakota' },
          { label: 'Tennessee', value: 'Tennessee' },
          { label: 'Texas', value: 'Texas' },
          { label: 'Utah', value: 'Utah' },
          { label: 'Vermont', value: 'Vermont' },
          { label: 'Virginia', value: 'Virginia' },
          { label: 'Washington', value: 'Washington' },
          { label: 'West Virginia', value: 'West Virginia' },
          { label: 'Wisconsin', value: 'Wisconsin' },
          { label: 'Wyoming', value: 'Wyoming' }
        ]
      },
      { key: 'leadsCompanyZipCode', label: 'Zip Code', type: 'text', placeholder: '12345', required: true }
    ]
  },
  //second step
  {
    title: 'Contact Info',
    fields: [
      { key: 'leadsFirstName', label: 'First Name', type: 'text', placeholder: 'John', required: true },
      { key: 'leadsMiddleName', label: 'Middle Name', type: 'text', placeholder: 'greg', required: false },
      { key: 'leadsLastName', label: 'Last Name', type: 'text', placeholder: 'Doe', required: true },
      { key: 'leadsTitle', label: 'Title', type: 'text', placeholder: 'Business Owner', required: false },
      { key: 'leadsContactEmail', label: 'Email', type: 'email', placeholder: 'email@example.com', required: true },
      { key: 'leadsContactPhoneNumber', label: 'Phone Number', type: 'tel', placeholder: '123-456-7890', required: true },
      { key: 'leadsContactMobileNumber', label: 'Mobile Number', type: 'tel', placeholder: '123-456-7890', required: false },
      {
        key: 'leadsContactCountry', label: 'Country', type: 'select', placeholder: 'Select Your Country', required: true, options: [
          { label: 'Afghanistan', value: 'Afghanistan' },
          { label: 'Albania', value: 'Albania' },
          { label: 'Algeria', value: 'Algeria' },
          { label: 'Andorra', value: 'Andorra' },
          { label: 'Angola', value: 'Angola' },
          { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
          { label: 'Argentina', value: 'Argentina' },
          { label: 'Armenia', value: 'Armenia' },
          { label: 'Australia', value: 'Australia' },
          { label: 'Austria', value: 'Austria' },
          { label: 'Azerbaijan', value: 'Azerbaijan' },
          { label: 'Bahamas', value: 'Bahamas' },
          { label: 'Bahrain', value: 'Bahrain' },
          { label: 'Bangladesh', value: 'Bangladesh' },
          { label: 'Barbados', value: 'Barbados' },
          { label: 'Belarus', value: 'Belarus' },
          { label: 'Belgium', value: 'Belgium' },
          { label: 'Belize', value: 'Belize' },
          { label: 'Benin', value: 'Benin' },
          { label: 'Bhutan', value: 'Bhutan' },
          { label: 'Bolivia', value: 'Bolivia' },
          { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
          { label: 'Botswana', value: 'Botswana' },
          { label: 'Brazil', value: 'Brazil' },
          { label: 'Brunei', value: 'Brunei' },
          { label: 'Bulgaria', value: 'Bulgaria' },
          { label: 'Burkina Faso', value: 'Burkina Faso' },
          { label: 'Burundi', value: 'Burundi' },
          { label: 'Cabo Verde', value: 'Cabo Verde' },
          { label: 'Cambodia', value: 'Cambodia' },
          { label: 'Cameroon', value: 'Cameroon' },
          { label: 'Canada', value: 'Canada' },
          { label: 'Central African Republic', value: 'Central African Republic' },
          { label: 'Chad', value: 'Chad' },
          { label: 'Chile', value: 'Chile' },
          { label: 'China', value: 'China' },
          { label: 'Colombia', value: 'Colombia' },
          { label: 'Comoros', value: 'Comoros' },
          { label: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)' },
          { label: 'Costa Rica', value: 'Costa Rica' },
          { label: 'Croatia', value: 'Croatia' },
          { label: 'Cuba', value: 'Cuba' },
          { label: 'Cyprus', value: 'Cyprus' },
          { label: 'Czech Republic', value: 'Czech Republic' },
          { label: 'Democratic Republic of the Congo', value: 'Democratic republic of the congo' },
          { label: 'Denmark', value: 'Denmark' },
          { label: 'Djibouti', value: 'Djibouti' },
          { label: 'Dominica', value: 'Dominica' },
          { label: 'Dominican Republic', value: 'Dominican Republic' },
          { label: 'Ecuador', value: 'Ecuador' },
          { label: 'Egypt', value: 'Egypt' },
          { label: 'El Salvador', value: 'El Salvador' },
          { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
          { label: 'Eritrea', value: 'Eritrea' },
          { label: 'Estonia', value: 'Estonia' },
          { label: 'Eswatini', value: 'Eswatini' },
          { label: 'Ethiopia', value: 'Ethiopia' },
          { label: 'Fiji', value: 'Fiji' },
          { label: 'Finland', value: 'Finland' },
          { label: 'France', value: 'France' },
          { label: 'Gabon', value: 'Gabon' },
          { label: 'Gambia', value: 'Gambia' },
          { label: 'Georgia', value: 'Georgia' },
          { label: 'Germany', value: 'Germany' },
          { label: 'Ghana', value: 'Ghana' },
          { label: 'Greece', value: 'Greece' },
          { label: 'Grenada', value: 'Grenada' },
          { label: 'Guatemala', value: 'Guatemala' },
          { label: 'Guinea', value: 'Guinea' },
          { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
          { label: 'Guyana', value: 'Guyana' },
          { label: 'Haiti', value: 'Haiti' },
          { label: 'Honduras', value: 'Honduras' },
          { label: 'Hungary', value: 'Hungary' },
          { label: 'Iceland', value: 'Iceland' },
          { label: 'India', value: 'India' },
          { label: 'Indonesia', value: 'Indonesia' },
          { label: 'Iran', value: 'Iran' },
          { label: 'Iraq', value: 'Iraq' },
          { label: 'Ireland', value: 'Ireland' },
          { label: 'Israel', value: 'Israel' },
          { label: 'Italy', value: 'Italy' },
          { label: 'Ivory Coast', value: 'Ivory Coast' },
          { label: 'Jamaica', value: 'Jamaica' },
          { label: 'Japan', value: 'Japan' },
          { label: 'Jordan', value: 'Jordan' },
          { label: 'Kazakhstan', value: 'Kazakhstan' },
          { label: 'Kenya', value: 'Kenya' },
          { label: 'Kiribati', value: 'Kiribati' },
          { label: 'Kuwait', value: 'Kuwait' },
          { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
          { label: 'Laos', value: 'Laos' },
          { label: 'Latvia', value: 'Latvia' },
          { label: 'Lebanon', value: 'Lebanon' },
          { label: 'Lesotho', value: 'Lesotho' },
          { label: 'Liberia', value: 'Liberia' },
          { label: 'Libya', value: 'Libya' },
          { label: 'Liechtenstein', value: 'Liechtenstein' },
          { label: 'Lithuania', value: 'Lithuania' },
          { label: 'Luxembourg', value: 'Luxembourg' },
          { label: 'Madagascar', value: 'Madagascar' },
          { label: 'Malawi', value: 'Malawi' },
          { label: 'Malaysia', value: 'Malaysia' },
          { label: 'Maldives', value: 'Maldives' },
          { label: 'Mali', value: 'Mali' },
          { label: 'Malta', value: 'Malta' },
          { label: 'Marshall Islands', value: 'Marshall Islands' },
          { label: 'Mauritania', value: 'Mauritania' },
          { label: 'Mauritius', value: 'Mauritius' },
          { label: 'Mexico', value: 'Mexico' },
          { label: 'Micronesia', value: 'Micronesia' },
          { label: 'Moldova', value: 'Moldova' },
          { label: 'Monaco', value: 'Monaco' },
          { label: 'Mongolia', value: 'Mongolia' },
          { label: 'Montenegro', value: 'Montenegro' },
          { label: 'Morocco', value: 'Morocco' },
          { label: 'Mozambique', value: 'Mozambique' },
          { label: 'Myanmar', value: 'Myanmar' },
          { label: 'Namibia', value: 'Namibia' },
          { label: 'Nauru', value: 'Nauru' },
          { label: 'Nepal', value: 'Nepal' },
          { label: 'Netherlands', value: 'Netherlands' },
          { label: 'New Zealand', value: 'New Zealand' },
          { label: 'Nicaragua', value: 'Nicaragua' },
          { label: 'Niger', value: 'Niger' },
          { label: 'Nigeria', value: 'Nigeria' },
          { label: 'North Korea', value: 'North Korea' },
          { label: 'North Macedonia', value: 'North macedonia' },
          { label: 'Norway', value: 'Norway' },
          { label: 'Oman', value: 'Oman' },
          { label: 'Pakistan', value: 'Pakistan' },
          { label: 'Palau', value: 'Palau' },
          { label: 'Palestine', value: 'Palestine' },
          { label: 'Panama', value: 'Panama' },
          { label: 'Papua New Guinea', value: 'Papua New Guinea' },
          { label: 'Paraguay', value: 'Paraguay' },
          { label: 'Peru', value: 'Peru' },
          { label: 'Philippines', value: 'Philippines' },
          { label: 'Poland', value: 'Poland' },
          { label: 'Portugal', value: 'Portugal' },
          { label: 'Qatar', value: 'Qatar' },
          { label: 'Romania', value: 'Romania' },
          { label: 'Russia', value: 'Russia' },
          { label: 'Rwanda', value: 'Rwanda' },
          { label: 'Saint Kitts and Nevis', value: 'Saint Kitts ad Nevis' },
          { label: 'Saint Lucia', value: 'saint lucia' },
          { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and The Grenadines' },
          { label: 'Samoa', value: 'Samoa' },
          { label: 'San Marino', value: 'San Marino' },
          { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
          { label: 'Saudi Arabia', value: 'Saudi Arabia' },
          { label: 'Senegal', value: 'Senegal' },
          { label: 'Serbia', value: 'Serbia' },
          { label: 'Seychelles', value: 'Seychelles' },
          { label: 'Sierra Leone', value: 'Sierra Leone' },
          { label: 'Singapore', value: 'Singapore' },
          { label: 'Slovakia', value: 'Slovakia' },
          { label: 'Slovenia', value: 'Slovenia' },
          { label: 'Solomon Islands', value: 'Solomon Islands' },
          { label: 'Somalia', value: 'Somalia' },
          { label: 'South Africa', value: 'South Africa' },
          { label: 'South Korea', value: 'South Korea' },
          { label: 'South Sudan', value: 'South Sudan' },
          { label: 'Spain', value: 'Spain' },
          { label: 'Sri Lanka', value: 'Sri Lanka' },
          { label: 'Sudan', value: 'Sudan' },
          { label: 'Suriname', value: 'Suriname' },
          { label: 'Sweden', value: 'Sweden' },
          { label: 'Switzerland', value: 'Switzerland' },
          { label: 'Syria', value: 'Syria' },
          { label: 'Taiwan', value: 'Taiwan' },
          { label: 'Tajikistan', value: 'Tajikistan' },
          { label: 'Tanzania', value: 'Tanzania' },
          { label: 'Thailand', value: 'Thailand' },
          { label: 'Timor-Leste', value: 'Timor-Leste' },
          { label: 'Togo', value: 'Togo' },
          { label: 'Tonga', value: 'Tonga' },
          { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
          { label: 'Tunisia', value: 'Tunisia' },
          { label: 'Turkey', value: 'Turkey' },
          { label: 'Turkmenistan', value: 'Turkmenistan' },
          { label: 'Tuvalu', value: 'Tuvalu' },
          { label: 'Uganda', value: 'Uganda' },
          { label: 'Ukraine', value: 'Ukraine' },
          { label: 'United Arab Emirates', value: 'United Arab Emirates' },
          { label: 'United Kingdom', value: 'United Kingdom' },
          { label: 'United States', value: 'United States' },
          { label: 'Uruguay', value: 'Uruguay' },
          { label: 'Uzbekistan', value: 'Uzbekistan' },
          { label: 'Vanuatu', value: 'Vanuatu' },
          { label: 'Vatican City', value: 'Vatican city' },
          { label: 'Venezuela', value: 'Venezuela' },
          { label: 'Vietnam', value: 'Vietnam' },
          { label: 'Yemen', value: 'Yemen' },
          { label: 'Zambia', value: 'Zambia' },
          { label: 'Zimbabwe', value: 'Zimbabwe' }
        ]
      },
      { key: 'leadsContactAddress1', label: 'Address 1', type: 'text', placeholder: '123 Main St, City, State, Zip', required: true },
      { key: 'leadsContactAddress2', label: 'Address 2', type: 'text', placeholder: 'Apartment, Suite, etc.', required: false },
      { key: 'leadsContactCity', label: 'City', type: 'text', placeholder: 'Los Angeles', required: true },
      {
        key: 'leadsContactState', label: 'State', type: 'select', placeholder: 'Select State', required: true, options: [
          { label: 'Alabama', value: 'Alabama' },
          { label: 'Alaska', value: 'Alaska' },
          { label: 'Arizona', value: 'Arizona' },
          { label: 'Arkansas', value: 'Arkansas' },
          { label: 'California', value: 'California' },
          { label: 'Colorado', value: 'Colorado' },
          { label: 'Connecticut', value: 'Connecticut' },
          { label: 'Delaware', value: 'Delaware' },
          { label: 'Florida', value: 'Florida' },
          { label: 'Georgia', value: 'Georgia' },
          { label: 'Hawaii', value: 'Hawaii' },
          { label: 'Idaho', value: 'Idaho' },
          { label: 'Illinois', value: 'Illinois' },
          { label: 'Indiana', value: 'Indiana' },
          { label: 'Iowa', value: 'Iowa' },
          { label: 'Kansas', value: 'Kansas' },
          { label: 'Kentucky', value: 'Kentucky' },
          { label: 'Louisiana', value: 'Louisiana' },
          { label: 'Maine', value: 'Maine' },
          { label: 'Maryland', value: 'Maryland' },
          { label: 'Massachusetts', value: 'Massachusetts' },
          { label: 'Michigan', value: 'Michigan' },
          { label: 'Minnesota', value: 'Minnesota' },
          { label: 'Mississippi', value: 'Mississippi' },
          { label: 'Missouri', value: 'Missouri' },
          { label: 'Montana', value: 'Montana' },
          { label: 'Nebraska', value: 'Nebraska' },
          { label: 'Nevada', value: 'Nevada' },
          { label: 'New Hampshire', value: 'New Hampshire' },
          { label: 'New Jersey', value: 'New Jersey' },
          { label: 'New Mexico', value: 'New Mexico' },
          { label: 'New York', value: 'New York' },
          { label: 'North Carolina', value: 'North Carolina' },
          { label: 'North Dakota', value: 'North Dakota' },
          { label: 'Ohio', value: 'Ohio' },
          { label: 'Oklahoma', value: 'Oklahoma' },
          { label: 'Oregon', value: 'Oregon' },
          { label: 'Pennsylvania', value: 'Pennsylvania' },
          { label: 'Rhode Island', value: 'Rhode Island' },
          { label: 'South Carolina', value: 'South Carolina' },
          { label: 'South Dakota', value: 'South Dakota' },
          { label: 'Tennessee', value: 'Tennessee' },
          { label: 'Texas', value: 'Texas' },
          { label: 'Utah', value: 'Utah' },
          { label: 'Vermont', value: 'Vermont' },
          { label: 'Virginia', value: 'Virginia' },
          { label: 'Washington', value: 'Washington' },
          { label: 'West Virginia', value: 'West Virginia' },
          { label: 'Wisconsin', value: 'Wisconsin' },
          { label: 'Wyoming', value: 'Wyoming' }
        ]
      },
      { key: 'leadsContactZipCode', label: 'Zip Code', type: 'text', placeholder: '12345', required: true }
    ]
  },
  {
    title: 'Additional Info',
    fields: [
      {
        key: 'commercialOrConsumer', label: 'Commercial/Consumer', type: 'select', placeholder: '', required: true, options: [
          { label: 'Commercial', value: 'Commercial' },
          { label: 'Consumer', value: 'Consumer' },
          { label: 'Both', value: 'Both' },
        ]
      },
      {
        key: 'referredBy', label: 'Referred By', type: 'select', placeholder: '', options: [
          { label: 'Google', value: 'google' },
          { label: 'Referral ', value: 'referral' },
          { label: 'Branch', value: 'branch' },
          { label: 'Old Email', value: 'oldEmail' },
          { label: 'Existing Client', value: 'existingClient' },
        ], required: false
      },
      { key: 'leadsMoneyExpected', label: 'Money Expected', type: 'number', placeholder: '10000', required: false },
      { key: 'clientAccountsExpected', label: 'Accounts Expected', type: 'number', placeholder: '5', required: false },
      { key: 'leadsClientSize', label: 'Client Size', type: 'number', placeholder: '50', required: false },
      { key: 'underOneYear', label: 'Under One Year', type: 'number', placeholder: '50%', required: true },
      { key: 'overOneYear', label: 'over One Year', type: 'number', placeholder: '100', required: true },
      { key: 'legalAndUnder1000', label: 'Legal and Under 1000', type: 'number', placeholder: '100', required: true },
      { key: 'interest', label: 'Interest', type: 'dual-number', placeholder: '100', required: true },
      { key: 'lateFees', label: 'Late Fees', type: 'dual-number', placeholder: '100', required: true },
      {
        key: 'cardConvenienceFee', label: 'Card Convenience Fee', type: 'radio',  options: [
          { label: 'Agency', value: 'Agency' },
          { label: 'Debtor', value: 'Debtor' },
          { label: 'Client', value: 'Client' },
        ]
      },
      { key: 'nextFollowUp', label: 'Next Follow Up', type: 'datetime-local', placeholder: '', required: false },
    ]
  }
];

export const clientsSteps = [
  //first step
  {
    title: 'Company Info',
    fields: [
      { key: 'clientCompanyName', label: 'Company Name', type: 'text', placeholder: 'Company Name', required: true },
      {
        key: 'clientMedical', label: 'Medical', type: 'select', placeholder: 'Please Specify', options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ]
      },
      {
        key: 'clientBusinessType', label: 'Business Type', type: 'select', placeholder: 'Select Business Type', options: [
          { label: 'Retail', value: 'retail' },
          { label: 'Wholesale', value: 'wholesale' },
          { label: 'Service', value: 'service' },
          { label: 'Manufacturing', value: 'manufacturing' },
          { label: 'Other', value: 'other' }
        ]
      },
      { key: 'clientWebsite', label: 'Website', type: 'url', placeholder: 'https://example.com', required: false },
      { key: 'clientCompanyEmail', label: 'Email', type: 'email', placeholder: 'email@example.com', required: true },
      { key: 'clientCompanyPhoneNumber', label: 'Phone Number', type: 'tel', placeholder: '123-456-7890', required: true },
      { key: 'clientFaxNumber', label: 'Fax Number', type: 'tel', placeholder: '123-456-7890', required: false },
      {
        key: 'clientCompanyCountry', label: 'Country', type: 'select', placeholder: 'Select Your Country', required: true, options: [
          { label: 'Afghanistan', value: 'afghanistan' },
          { label: 'Albania', value: 'albania' },
          { label: 'Algeria', value: 'algeria' },
          { label: 'Andorra', value: 'andorra' },
          { label: 'Angola', value: 'angola' },
          { label: 'Antigua and Barbuda', value: 'antigua and barbuda' },
          { label: 'Argentina', value: 'argentina' },
          { label: 'Armenia', value: 'armenia' },
          { label: 'Australia', value: 'australia' },
          { label: 'Austria', value: 'austria' },
          { label: 'Azerbaijan', value: 'azerbaijan' },
          { label: 'Bahamas', value: 'bahamas' },
          { label: 'Bahrain', value: 'bahrain' },
          { label: 'Bangladesh', value: 'bangladesh' },
          { label: 'Barbados', value: 'barbados' },
          { label: 'Belarus', value: 'belarus' },
          { label: 'Belgium', value: 'belgium' },
          { label: 'Belize', value: 'belize' },
          { label: 'Benin', value: 'benin' },
          { label: 'Bhutan', value: 'bhutan' },
          { label: 'Bolivia', value: 'bolivia' },
          { label: 'Bosnia and Herzegovina', value: 'bosnia and herzegovina' },
          { label: 'Botswana', value: 'botswana' },
          { label: 'Brazil', value: 'brazil' },
          { label: 'Brunei', value: 'brunei' },
          { label: 'Bulgaria', value: 'bulgaria' },
          { label: 'Burkina Faso', value: 'burkina faso' },
          { label: 'Burundi', value: 'burundi' },
          { label: 'Cabo Verde', value: 'cabo verde' },
          { label: 'Cambodia', value: 'cambodia' },
          { label: 'Cameroon', value: 'cameroon' },
          { label: 'Canada', value: 'canada' },
          { label: 'Central African Republic', value: 'central african republic' },
          { label: 'Chad', value: 'chad' },
          { label: 'Chile', value: 'chile' },
          { label: 'China', value: 'china' },
          { label: 'Colombia', value: 'colombia' },
          { label: 'Comoros', value: 'comoros' },
          { label: 'Congo (Congo-Brazzaville)', value: 'congo (congo-brazzaville)' },
          { label: 'Costa Rica', value: 'costa rica' },
          { label: 'Croatia', value: 'croatia' },
          { label: 'Cuba', value: 'cuba' },
          { label: 'Cyprus', value: 'cyprus' },
          { label: 'Czech Republic', value: 'czech republic' },
          { label: 'Democratic Republic of the Congo', value: 'democratic republic of the congo' },
          { label: 'Denmark', value: 'denmark' },
          { label: 'Djibouti', value: 'djibouti' },
          { label: 'Dominica', value: 'dominica' },
          { label: 'Dominican Republic', value: 'dominican republic' },
          { label: 'Ecuador', value: 'ecuador' },
          { label: 'Egypt', value: 'egypt' },
          { label: 'El Salvador', value: 'el salvador' },
          { label: 'Equatorial Guinea', value: 'equatorial guinea' },
          { label: 'Eritrea', value: 'eritrea' },
          { label: 'Estonia', value: 'estonia' },
          { label: 'Eswatini', value: 'eswatini' },
          { label: 'Ethiopia', value: 'ethiopia' },
          { label: 'Fiji', value: 'fiji' },
          { label: 'Finland', value: 'finland' },
          { label: 'France', value: 'france' },
          { label: 'Gabon', value: 'gabon' },
          { label: 'Gambia', value: 'gambia' },
          { label: 'Georgia', value: 'georgia' },
          { label: 'Germany', value: 'germany' },
          { label: 'Ghana', value: 'ghana' },
          { label: 'Greece', value: 'greece' },
          { label: 'Grenada', value: 'grenada' },
          { label: 'Guatemala', value: 'guatemala' },
          { label: 'Guinea', value: 'guinea' },
          { label: 'Guinea-Bissau', value: 'guinea-bissau' },
          { label: 'Guyana', value: 'guyana' },
          { label: 'Haiti', value: 'haiti' },
          { label: 'Honduras', value: 'honduras' },
          { label: 'Hungary', value: 'hungary' },
          { label: 'Iceland', value: 'iceland' },
          { label: 'India', value: 'india' },
          { label: 'Indonesia', value: 'indonesia' },
          { label: 'Iran', value: 'iran' },
          { label: 'Iraq', value: 'iraq' },
          { label: 'Ireland', value: 'ireland' },
          { label: 'Israel', value: 'israel' },
          { label: 'Italy', value: 'italy' },
          { label: 'Ivory Coast', value: 'ivory coast' },
          { label: 'Jamaica', value: 'jamaica' },
          { label: 'Japan', value: 'japan' },
          { label: 'Jordan', value: 'jordan' },
          { label: 'Kazakhstan', value: 'kazakhstan' },
          { label: 'Kenya', value: 'kenya' },
          { label: 'Kiribati', value: 'kiribati' },
          { label: 'Kuwait', value: 'kuwait' },
          { label: 'Kyrgyzstan', value: 'kyrgyzstan' },
          { label: 'Laos', value: 'laos' },
          { label: 'Latvia', value: 'latvia' },
          { label: 'Lebanon', value: 'lebanon' },
          { label: 'Lesotho', value: 'lesotho' },
          { label: 'Liberia', value: 'liberia' },
          { label: 'Libya', value: 'libya' },
          { label: 'Liechtenstein', value: 'liechtenstein' },
          { label: 'Lithuania', value: 'lithuania' },
          { label: 'Luxembourg', value: 'luxembourg' },
          { label: 'Madagascar', value: 'madagascar' },
          { label: 'Malawi', value: 'malawi' },
          { label: 'Malaysia', value: 'malaysia' },
          { label: 'Maldives', value: 'maldives' },
          { label: 'Mali', value: 'mali' },
          { label: 'Malta', value: 'malta' },
          { label: 'Marshall Islands', value: 'marshall islands' },
          { label: 'Mauritania', value: 'mauritania' },
          { label: 'Mauritius', value: 'mauritius' },
          { label: 'Mexico', value: 'mexico' },
          { label: 'Micronesia', value: 'micronesia' },
          { label: 'Moldova', value: 'moldova' },
          { label: 'Monaco', value: 'monaco' },
          { label: 'Mongolia', value: 'mongolia' },
          { label: 'Montenegro', value: 'montenegro' },
          { label: 'Morocco', value: 'morocco' },
          { label: 'Mozambique', value: 'mozambique' },
          { label: 'Myanmar', value: 'myanmar' },
          { label: 'Namibia', value: 'namibia' },
          { label: 'Nauru', value: 'nauru' },
          { label: 'Nepal', value: 'nepal' },
          { label: 'Netherlands', value: 'netherlands' },
          { label: 'New Zealand', value: 'new zealand' },
          { label: 'Nicaragua', value: 'nicaragua' },
          { label: 'Niger', value: 'niger' },
          { label: 'Nigeria', value: 'nigeria' },
          { label: 'North Korea', value: 'north korea' },
          { label: 'North Macedonia', value: 'north macedonia' },
          { label: 'Norway', value: 'norway' },
          { label: 'Oman', value: 'oman' },
          { label: 'Pakistan', value: 'pakistan' },
          { label: 'Palau', value: 'palau' },
          { label: 'Palestine', value: 'palestine' },
          { label: 'Panama', value: 'panama' },
          { label: 'Papua New Guinea', value: 'papua new guinea' },
          { label: 'Paraguay', value: 'paraguay' },
          { label: 'Peru', value: 'peru' },
          { label: 'Philippines', value: 'philippines' },
          { label: 'Poland', value: 'poland' },
          { label: 'Portugal', value: 'portugal' },
          { label: 'Qatar', value: 'qatar' },
          { label: 'Romania', value: 'romania' },
          { label: 'Russia', value: 'russia' },
          { label: 'Rwanda', value: 'rwanda' },
          { label: 'Saint Kitts and Nevis', value: 'saint kitts and nevis' },
          { label: 'Saint Lucia', value: 'saint lucia' },
          { label: 'Saint Vincent and the Grenadines', value: 'saint vincent and the grenadines' },
          { label: 'Samoa', value: 'samoa' },
          { label: 'San Marino', value: 'san marino' },
          { label: 'Sao Tome and Principe', value: 'sao tome and principe' },
          { label: 'Saudi Arabia', value: 'saudi arabia' },
          { label: 'Senegal', value: 'senegal' },
          { label: 'Serbia', value: 'serbia' },
          { label: 'Seychelles', value: 'seychelles' },
          { label: 'Sierra Leone', value: 'sierra leone' },
          { label: 'Singapore', value: 'singapore' },
          { label: 'Slovakia', value: 'slovakia' },
          { label: 'Slovenia', value: 'slovenia' },
          { label: 'Solomon Islands', value: 'solomon islands' },
          { label: 'Somalia', value: 'somalia' },
          { label: 'South Africa', value: 'south africa' },
          { label: 'South Korea', value: 'south korea' },
          { label: 'South Sudan', value: 'south sudan' },
          { label: 'Spain', value: 'spain' },
          { label: 'Sri Lanka', value: 'sri lanka' },
          { label: 'Sudan', value: 'sudan' },
          { label: 'Suriname', value: 'suriname' },
          { label: 'Sweden', value: 'sweden' },
          { label: 'Switzerland', value: 'switzerland' },
          { label: 'Syria', value: 'syria' },
          { label: 'Taiwan', value: 'taiwan' },
          { label: 'Tajikistan', value: 'tajikistan' },
          { label: 'Tanzania', value: 'tanzania' },
          { label: 'Thailand', value: 'thailand' },
          { label: 'Timor-Leste', value: 'timor-leste' },
          { label: 'Togo', value: 'togo' },
          { label: 'Tonga', value: 'tonga' },
          { label: 'Trinidad and Tobago', value: 'trinidad and tobago' },
          { label: 'Tunisia', value: 'tunisia' },
          { label: 'Turkey', value: 'turkey' },
          { label: 'Turkmenistan', value: 'turkmenistan' },
          { label: 'Tuvalu', value: 'tuvalu' },
          { label: 'Uganda', value: 'uganda' },
          { label: 'Ukraine', value: 'ukraine' },
          { label: 'United Arab Emirates', value: 'united arab emirates' },
          { label: 'United Kingdom', value: 'united kingdom' },
          { label: 'United States', value: 'united states' },
          { label: 'Uruguay', value: 'uruguay' },
          { label: 'Uzbekistan', value: 'uzbekistan' },
          { label: 'Vanuatu', value: 'vanuatu' },
          { label: 'Vatican City', value: 'vatican city' },
          { label: 'Venezuela', value: 'venezuela' },
          { label: 'Vietnam', value: 'vietnam' },
          { label: 'Yemen', value: 'yemen' },
          { label: 'Zambia', value: 'zambia' },
          { label: 'Zimbabwe', value: 'zimbabwe' }
        ]
      },
      { key: 'clientCompanyAddress1', label: 'Address 1', type: 'text', placeholder: '123 Main St, City, State, Zip', required: true },
      { key: 'clientCompanyAddress2', label: 'Address 2', type: 'text', placeholder: 'Apartment, Suite, etc.', required: false },
      { key: 'clientCompanyCity', label: 'City', type: 'text', placeholder: 'Los Angeles', required: true },
      {
        key: 'clientCompanyState', label: 'State', type: 'select', placeholder: 'Select State', options: [
          { label: 'Alabama', value: 'alabama' },
          { label: 'Alaska', value: 'alaska' },
          { label: 'Arizona', value: 'arizona' },
          { label: 'Arkansas', value: 'arkansas' },
          { label: 'California', value: 'california' },
          { label: 'Colorado', value: 'colorado' },
          { label: 'Connecticut', value: 'connecticut' },
          { label: 'Delaware', value: 'delaware' },
          { label: 'Florida', value: 'florida' },
          { label: 'Georgia', value: 'georgia' },
          { label: 'Hawaii', value: 'hawaii' },
          { label: 'Idaho', value: 'idaho' },
          { label: 'Illinois', value: 'illinois' },
          { label: 'Indiana', value: 'indiana' },
          { label: 'Iowa', value: 'iowa' },
          { label: 'Kansas', value: 'kansas' },
          { label: 'Kentucky', value: 'kentucky' },
          { label: 'Louisiana', value: 'louisiana' },
          { label: 'Maine', value: 'maine' },
          { label: 'Maryland', value: 'maryland' },
          { label: 'Massachusetts', value: 'massachusetts' },
          { label: 'Michigan', value: 'michigan' },
          { label: 'Minnesota', value: 'minnesota' },
          { label: 'Mississippi', value: 'mississippi' },
          { label: 'Missouri', value: 'missouri' },
          { label: 'Montana', value: 'montana' },
          { label: 'Nebraska', value: 'nebraska' },
          { label: 'Nevada', value: 'nevada' },
          { label: 'New Hampshire', value: 'new hampshire' },
          { label: 'New Jersey', value: 'new jersey' },
          { label: 'New Mexico', value: 'new mexico' },
          { label: 'New York', value: 'new york' },
          { label: 'North Carolina', value: 'north carolina' },
          { label: 'North Dakota', value: 'north dakota' },
          { label: 'Ohio', value: 'ohio' },
          { label: 'Oklahoma', value: 'oklahoma' },
          { label: 'Oregon', value: 'oregon' },
          { label: 'Pennsylvania', value: 'pennsylvania' },
          { label: 'Rhode Island', value: 'rhode island' },
          { label: 'South Carolina', value: 'south carolina' },
          { label: 'South Dakota', value: 'south dakota' },
          { label: 'Tennessee', value: 'tennessee' },
          { label: 'Texas', value: 'texas' },
          { label: 'Utah', value: 'utah' },
          { label: 'Vermont', value: 'vermont' },
          { label: 'Virginia', value: 'virginia' },
          { label: 'Washington', value: 'washington' },
          { label: 'West Virginia', value: 'west virginia' },
          { label: 'Wisconsin', value: 'wisconsin' },
          { label: 'Wyoming', value: 'wyoming' }
        ]
      },
      { key: 'clientCompanyZipCode', label: 'Zip Code', type: 'text', placeholder: '12345', required: true }
    ]
  },
  //second step
  {
    title: 'Contact Info',
    fields: [
      { key: 'clientFirstName', label: 'First Name', type: 'text', placeholder: 'John', required: true },
      { key: 'clientMiddleName', label: 'Middle Name', type: 'text', placeholder: 'greg', required: false },
      { key: 'clientLastName', label: 'Last Name', type: 'text', placeholder: 'Doe', required: true },
      { key: 'clientTitle', label: 'Title', type: 'text', placeholder: 'Business Owner', required: false },
      { key: 'clientContactEmail', label: 'Email', type: 'email', placeholder: 'email@example.com', required: true },
      { key: 'clientContactPhone', label: 'Phone Number', type: 'tel', placeholder: '123-456-7890', required: true },
      { key: 'clientContactMobileNumber', label: 'Mobile Number', type: 'tel', placeholder: '123-456-7890', required: false },
      {
        key: 'clientContactCountry', label: 'Country', type: 'select', placeholder: 'Select Your Country', required: true, options: [
          { label: 'Afghanistan', value: 'afghanistan' },
          { label: 'Albania', value: 'albania' },
          { label: 'Algeria', value: 'algeria' },
          { label: 'Andorra', value: 'andorra' },
          { label: 'Angola', value: 'angola' },
          { label: 'Antigua and Barbuda', value: 'antigua and barbuda' },
          { label: 'Argentina', value: 'argentina' },
          { label: 'Armenia', value: 'armenia' },
          { label: 'Australia', value: 'australia' },
          { label: 'Austria', value: 'austria' },
          { label: 'Azerbaijan', value: 'azerbaijan' },
          { label: 'Bahamas', value: 'bahamas' },
          { label: 'Bahrain', value: 'bahrain' },
          { label: 'Bangladesh', value: 'bangladesh' },
          { label: 'Barbados', value: 'barbados' },
          { label: 'Belarus', value: 'belarus' },
          { label: 'Belgium', value: 'belgium' },
          { label: 'Belize', value: 'belize' },
          { label: 'Benin', value: 'benin' },
          { label: 'Bhutan', value: 'bhutan' },
          { label: 'Bolivia', value: 'bolivia' },
          { label: 'Bosnia and Herzegovina', value: 'bosnia and herzegovina' },
          { label: 'Botswana', value: 'botswana' },
          { label: 'Brazil', value: 'brazil' },
          { label: 'Brunei', value: 'brunei' },
          { label: 'Bulgaria', value: 'bulgaria' },
          { label: 'Burkina Faso', value: 'burkina faso' },
          { label: 'Burundi', value: 'burundi' },
          { label: 'Cabo Verde', value: 'cabo verde' },
          { label: 'Cambodia', value: 'cambodia' },
          { label: 'Cameroon', value: 'cameroon' },
          { label: 'Canada', value: 'canada' },
          { label: 'Central African Republic', value: 'central african republic' },
          { label: 'Chad', value: 'chad' },
          { label: 'Chile', value: 'chile' },
          { label: 'China', value: 'china' },
          { label: 'Colombia', value: 'colombia' },
          { label: 'Comoros', value: 'comoros' },
          { label: 'Congo (Congo-Brazzaville)', value: 'congo (congo-brazzaville)' },
          { label: 'Costa Rica', value: 'costa rica' },
          { label: 'Croatia', value: 'croatia' },
          { label: 'Cuba', value: 'cuba' },
          { label: 'Cyprus', value: 'cyprus' },
          { label: 'Czech Republic', value: 'czech republic' },
          { label: 'Democratic Republic of the Congo', value: 'democratic republic of the congo' },
          { label: 'Denmark', value: 'denmark' },
          { label: 'Djibouti', value: 'djibouti' },
          { label: 'Dominica', value: 'dominica' },
          { label: 'Dominican Republic', value: 'dominican republic' },
          { label: 'Ecuador', value: 'ecuador' },
          { label: 'Egypt', value: 'egypt' },
          { label: 'El Salvador', value: 'el salvador' },
          { label: 'Equatorial Guinea', value: 'equatorial guinea' },
          { label: 'Eritrea', value: 'eritrea' },
          { label: 'Estonia', value: 'estonia' },
          { label: 'Eswatini', value: 'eswatini' },
          { label: 'Ethiopia', value: 'ethiopia' },
          { label: 'Fiji', value: 'fiji' },
          { label: 'Finland', value: 'finland' },
          { label: 'France', value: 'france' },
          { label: 'Gabon', value: 'gabon' },
          { label: 'Gambia', value: 'gambia' },
          { label: 'Georgia', value: 'georgia' },
          { label: 'Germany', value: 'germany' },
          { label: 'Ghana', value: 'ghana' },
          { label: 'Greece', value: 'greece' },
          { label: 'Grenada', value: 'grenada' },
          { label: 'Guatemala', value: 'guatemala' },
          { label: 'Guinea', value: 'guinea' },
          { label: 'Guinea-Bissau', value: 'guinea-bissau' },
          { label: 'Guyana', value: 'guyana' },
          { label: 'Haiti', value: 'haiti' },
          { label: 'Honduras', value: 'honduras' },
          { label: 'Hungary', value: 'hungary' },
          { label: 'Iceland', value: 'iceland' },
          { label: 'India', value: 'india' },
          { label: 'Indonesia', value: 'indonesia' },
          { label: 'Iran', value: 'iran' },
          { label: 'Iraq', value: 'iraq' },
          { label: 'Ireland', value: 'ireland' },
          { label: 'Israel', value: 'israel' },
          { label: 'Italy', value: 'italy' },
          { label: 'Ivory Coast', value: 'ivory coast' },
          { label: 'Jamaica', value: 'jamaica' },
          { label: 'Japan', value: 'japan' },
          { label: 'Jordan', value: 'jordan' },
          { label: 'Kazakhstan', value: 'kazakhstan' },
          { label: 'Kenya', value: 'kenya' },
          { label: 'Kiribati', value: 'kiribati' },
          { label: 'Kuwait', value: 'kuwait' },
          { label: 'Kyrgyzstan', value: 'kyrgyzstan' },
          { label: 'Laos', value: 'laos' },
          { label: 'Latvia', value: 'latvia' },
          { label: 'Lebanon', value: 'lebanon' },
          { label: 'Lesotho', value: 'lesotho' },
          { label: 'Liberia', value: 'liberia' },
          { label: 'Libya', value: 'libya' },
          { label: 'Liechtenstein', value: 'liechtenstein' },
          { label: 'Lithuania', value: 'lithuania' },
          { label: 'Luxembourg', value: 'luxembourg' },
          { label: 'Madagascar', value: 'madagascar' },
          { label: 'Malawi', value: 'malawi' },
          { label: 'Malaysia', value: 'malaysia' },
          { label: 'Maldives', value: 'maldives' },
          { label: 'Mali', value: 'mali' },
          { label: 'Malta', value: 'malta' },
          { label: 'Marshall Islands', value: 'marshall islands' },
          { label: 'Mauritania', value: 'mauritania' },
          { label: 'Mauritius', value: 'mauritius' },
          { label: 'Mexico', value: 'mexico' },
          { label: 'Micronesia', value: 'micronesia' },
          { label: 'Moldova', value: 'moldova' },
          { label: 'Monaco', value: 'monaco' },
          { label: 'Mongolia', value: 'mongolia' },
          { label: 'Montenegro', value: 'montenegro' },
          { label: 'Morocco', value: 'morocco' },
          { label: 'Mozambique', value: 'mozambique' },
          { label: 'Myanmar', value: 'myanmar' },
          { label: 'Namibia', value: 'namibia' },
          { label: 'Nauru', value: 'nauru' },
          { label: 'Nepal', value: 'nepal' },
          { label: 'Netherlands', value: 'netherlands' },
          { label: 'New Zealand', value: 'new zealand' },
          { label: 'Nicaragua', value: 'nicaragua' },
          { label: 'Niger', value: 'niger' },
          { label: 'Nigeria', value: 'nigeria' },
          { label: 'North Korea', value: 'north korea' },
          { label: 'North Macedonia', value: 'north macedonia' },
          { label: 'Norway', value: 'norway' },
          { label: 'Oman', value: 'oman' },
          { label: 'Pakistan', value: 'pakistan' },
          { label: 'Palau', value: 'palau' },
          { label: 'Palestine', value: 'palestine' },
          { label: 'Panama', value: 'panama' },
          { label: 'Papua New Guinea', value: 'papua new guinea' },
          { label: 'Paraguay', value: 'paraguay' },
          { label: 'Peru', value: 'peru' },
          { label: 'Philippines', value: 'philippines' },
          { label: 'Poland', value: 'poland' },
          { label: 'Portugal', value: 'portugal' },
          { label: 'Qatar', value: 'qatar' },
          { label: 'Romania', value: 'romania' },
          { label: 'Russia', value: 'russia' },
          { label: 'Rwanda', value: 'rwanda' },
          { label: 'Saint Kitts and Nevis', value: 'saint kitts and nevis' },
          { label: 'Saint Lucia', value: 'saint lucia' },
          { label: 'Saint Vincent and the Grenadines', value: 'saint vincent and the grenadines' },
          { label: 'Samoa', value: 'samoa' },
          { label: 'San Marino', value: 'san marino' },
          { label: 'Sao Tome and Principe', value: 'sao tome and principe' },
          { label: 'Saudi Arabia', value: 'saudi arabia' },
          { label: 'Senegal', value: 'senegal' },
          { label: 'Serbia', value: 'serbia' },
          { label: 'Seychelles', value: 'seychelles' },
          { label: 'Sierra Leone', value: 'sierra leone' },
          { label: 'Singapore', value: 'singapore' },
          { label: 'Slovakia', value: 'slovakia' },
          { label: 'Slovenia', value: 'slovenia' },
          { label: 'Solomon Islands', value: 'solomon islands' },
          { label: 'Somalia', value: 'somalia' },
          { label: 'South Africa', value: 'south africa' },
          { label: 'South Korea', value: 'south korea' },
          { label: 'South Sudan', value: 'south sudan' },
          { label: 'Spain', value: 'spain' },
          { label: 'Sri Lanka', value: 'sri lanka' },
          { label: 'Sudan', value: 'sudan' },
          { label: 'Suriname', value: 'suriname' },
          { label: 'Sweden', value: 'sweden' },
          { label: 'Switzerland', value: 'switzerland' },
          { label: 'Syria', value: 'syria' },
          { label: 'Taiwan', value: 'taiwan' },
          { label: 'Tajikistan', value: 'tajikistan' },
          { label: 'Tanzania', value: 'tanzania' },
          { label: 'Thailand', value: 'thailand' },
          { label: 'Timor-Leste', value: 'timor-leste' },
          { label: 'Togo', value: 'togo' },
          { label: 'Tonga', value: 'tonga' },
          { label: 'Trinidad and Tobago', value: 'trinidad and tobago' },
          { label: 'Tunisia', value: 'tunisia' },
          { label: 'Turkey', value: 'turkey' },
          { label: 'Turkmenistan', value: 'turkmenistan' },
          { label: 'Tuvalu', value: 'tuvalu' },
          { label: 'Uganda', value: 'uganda' },
          { label: 'Ukraine', value: 'ukraine' },
          { label: 'United Arab Emirates', value: 'united arab emirates' },
          { label: 'United Kingdom', value: 'united kingdom' },
          { label: 'United States', value: 'united states' },
          { label: 'Uruguay', value: 'uruguay' },
          { label: 'Uzbekistan', value: 'uzbekistan' },
          { label: 'Vanuatu', value: 'vanuatu' },
          { label: 'Vatican City', value: 'vatican city' },
          { label: 'Venezuela', value: 'venezuela' },
          { label: 'Vietnam', value: 'vietnam' },
          { label: 'Yemen', value: 'yemen' },
          { label: 'Zambia', value: 'zambia' },
          { label: 'Zimbabwe', value: 'zimbabwe' }
        ]
      },
      { key: 'clientContactAddress1', label: 'Address 1', type: 'text', placeholder: '123 Main St, City, State, Zip', required: true },
      { key: 'clientContactAddress2', label: 'Address 2', type: 'text', placeholder: 'Apartment, Suite, etc.', required: false },
      { key: 'clientContactCity', label: 'City', type: 'text', placeholder: 'Los Angeles', required: true },
      {
        key: 'clientContactState', label: 'State', type: 'select', placeholder: 'Select State', required: true, options: [
          { label: 'Alabama', value: 'alabama' },
          { label: 'Alaska', value: 'alaska' },
          { label: 'Arizona', value: 'arizona' },
          { label: 'Arkansas', value: 'arkansas' },
          { label: 'California', value: 'california' },
          { label: 'Colorado', value: 'colorado' },
          { label: 'Connecticut', value: 'connecticut' },
          { label: 'Delaware', value: 'delaware' },
          { label: 'Florida', value: 'florida' },
          { label: 'Georgia', value: 'georgia' },
          { label: 'Hawaii', value: 'hawaii' },
          { label: 'Idaho', value: 'idaho' },
          { label: 'Illinois', value: 'illinois' },
          { label: 'Indiana', value: 'indiana' },
          { label: 'Iowa', value: 'iowa' },
          { label: 'Kansas', value: 'kansas' },
          { label: 'Kentucky', value: 'kentucky' },
          { label: 'Louisiana', value: 'louisiana' },
          { label: 'Maine', value: 'maine' },
          { label: 'Maryland', value: 'maryland' },
          { label: 'Massachusetts', value: 'massachusetts' },
          { label: 'Michigan', value: 'michigan' },
          { label: 'Minnesota', value: 'minnesota' },
          { label: 'Mississippi', value: 'mississippi' },
          { label: 'Missouri', value: 'missouri' },
          { label: 'Montana', value: 'montana' },
          { label: 'Nebraska', value: 'nebraska' },
          { label: 'Nevada', value: 'nevada' },
          { label: 'New Hampshire', value: 'new hampshire' },
          { label: 'New Jersey', value: 'new jersey' },
          { label: 'New Mexico', value: 'new mexico' },
          { label: 'New York', value: 'new york' },
          { label: 'North Carolina', value: 'north carolina' },
          { label: 'North Dakota', value: 'north dakota' },
          { label: 'Ohio', value: 'ohio' },
          { label: 'Oklahoma', value: 'oklahoma' },
          { label: 'Oregon', value: 'oregon' },
          { label: 'Pennsylvania', value: 'pennsylvania' },
          { label: 'Rhode Island', value: 'rhode island' },
          { label: 'South Carolina', value: 'south carolina' },
          { label: 'South Dakota', value: 'south dakota' },
          { label: 'Tennessee', value: 'tennessee' },
          { label: 'Texas', value: 'texas' },
          { label: 'Utah', value: 'utah' },
          { label: 'Vermont', value: 'vermont' },
          { label: 'Virginia', value: 'virginia' },
          { label: 'Washington', value: 'washington' },
          { label: 'West Virginia', value: 'west virginia' },
          { label: 'Wisconsin', value: 'wisconsin' },
          { label: 'Wyoming', value: 'wyoming' }
        ]
      },
      { key: 'clientContactZipCode', label: 'Zip Code', type: 'text', placeholder: '12345', required: true }
    ]
  },
  {
    title: 'Additional Info',
    fields: [
      {
        key: 'source', label: 'Source', type: 'select', placeholder: '', options: [
          { label: 'Referred', value: 'referred' },
          { label: 'Hunting', value: 'hunting' },
          { label: 'Parent', value: 'parent' },
          { label: 'Independent', value: 'independent' },
          { label: 'Subsidiary', value: 'sybsidiary' },
          { label: 'Branch', value: 'branch' },
          { label: 'Private', value: 'private' },
        ], required: false
      },
      { key: 'clientMoneyExpected', label: 'Money Expected', type: 'number', placeholder: '10000', required: false },
      { key: 'clientAccountsExpected', label: 'Accounts Expected', type: 'number', placeholder: '5', required: false },
      { key: 'clientClientSize', label: 'Client Size', type: 'number', placeholder: '50', required: false },
    ]
  }
];